# conda env create -f environment.yml

name: pfamfold

channels:
  - conda-forge
  - bioconda
  - defaults
  - kimlab

dependencies:
  # Python and core libraries
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy

  # Bioinformatics tools and libraries
  - biopython
  - pdb-tools
  - famsa
  - clipkit
  - fasttree
  - foldseek
  - stride

  # Parallel processing
  - joblib

  # Additional utilities
  - pip

  # Pip-installed packages (if any additional Python packages are needed)
  - pip:
      - multiprocess